// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCH9UPEqr7jVfBEvo6jH-mp0oZxTIOEqeo',
    appId: '1:796058398306:web:10ccb8d7b89f82319f2b3b',
    messagingSenderId: '796058398306',
    projectId: 'civixdatabase',
    authDomain: 'civixdatabase.firebaseapp.com',
    storageBucket: 'civixdatabase.firebasestorage.app',
    measurementId: 'G-WWCJW0KFX8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmtgTzGU8SipvBWmacwCu2vhDZWLf9_hM',
    appId: '1:796058398306:android:f84716faef8cb8be9f2b3b',
    messagingSenderId: '796058398306',
    projectId: 'civixdatabase',
    storageBucket: 'civixdatabase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBaJG6_SlpjOFJeQJ9VwTm5LeNinWg_H8',
    appId: '1:796058398306:ios:38162381bebf82769f2b3b',
    messagingSenderId: '796058398306',
    projectId: 'civixdatabase',
    storageBucket: 'civixdatabase.firebasestorage.app',
    iosBundleId: 'com.example.civix',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCH9UPEqr7jVfBEvo6jH-mp0oZxTIOEqeo',
    appId: '1:796058398306:web:169fbe70dce9d7dd9f2b3b',
    messagingSenderId: '796058398306',
    projectId: 'civixdatabase',
    authDomain: 'civixdatabase.firebaseapp.com',
    storageBucket: 'civixdatabase.firebasestorage.app',
    measurementId: 'G-PG9FNQP24E',
  );
}
